using Microsoft.EntityFrameworkCore;
using NetTopologySuite.Geometries;
using Planarian.Model.Database.Entities;
using Planarian.Model.Database.Entities.RidgeWalker;
using Planarian.Model.Shared;
using Planarian.Model.Shared.Helpers;
using Planarian.Modules.Caves.Revisions;
using Planarian.Modules.Import.Planning;
using Xunit;

namespace Planarian.Tests;

public sealed class CaveImportCompatibilityTests(PostgresIntegrationFixture fixture):IClassFixture<PostgresIntegrationFixture>
{
    [Fact] public async Task RequiredCaveNameIsRejected()=>await AssertPlanFails(",County A,A01,1,AA,,,,,,,,,,,,,,,false,,");
    [Fact] public async Task StateMatchingRemainsCaseSensitive()=>await AssertPlanFails("Bad State,County A,A01,7,aa,,,,,,,,,,,,,,,false,,");
    [Theory][InlineData(-1,1,1,1)][InlineData(1,-1,1,1)][InlineData(1,1,-1,1)][InlineData(1,1,1,-1)]
    public async Task NegativeNumbersRemainInvalid(double length,double depth,double pit,int pits)=>await AssertPlanFails($"Negative,County A,A01,9,AA,,,,{length},{depth},{pit},{pits},,,,,,,,false,,");
    [Fact] public async Task NonSyncDuplicateCountyNumberIsRejected()=>await AssertPlanFails("Duplicate,County A,A01,1,AA,,,,,,,,,,,,,,,false,,",false);
    [Fact] public async Task SyncDuplicateCompositeKeyIsRejected()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(SyncDuplicateCompositeKeyIsRejected));var t=await IntegrationTestData.SeedTenantAsync(d,'a');await using var db=d.CreateDbContext("a",t.AccountId);var p=new CaveImportPlanner(db,db.RequestUser);var row="First,County A,A01,1,AA,,,,,,,,,,,,,,,false,,";await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.CaveHeader+"\n"+row+"\n"+row.Replace("First","Second")+"\n");await Assert.ThrowsAnyAsync<Exception>(()=>p.PlanAsync(csv,true));}
    [Fact] public async Task CreationComparisonIsCaseSensitiveButResolutionIsInsensitive()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(CreationComparisonIsCaseSensitiveButResolutionIsInsensitive));var t=await IntegrationTestData.SeedTenantAsync(d,'a');string id;await using(var s=d.CreateDbContext("a",t.AccountId)){var tag=Tag(t.AccountId,"geology","Foo");s.TagTypes.Add(tag);await s.SaveChangesAsync();id=tag.Id;}await using var db=d.CreateDbContext("a",t.AccountId);var p=new CaveImportPlanner(db,db.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.CaveHeader+"\nCase,County A,A01,20,AA,,,,,,,1,foo,,,,,,,false,,\n");var plan=await p.PlanAsync(csv,false);Assert.Contains(plan.TagCreations,x=>x.Name=="foo");Assert.Contains(Assert.Single(plan.Caves).Tags,x=>x.TagTypeId==id);}
    [Fact] public async Task ForeignCustomTagIsIneligible()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(ForeignCustomTagIsIneligible));var a=await IntegrationTestData.SeedTenantAsync(d,'a');var b=await IntegrationTestData.SeedTenantAsync(d,'b');string id;await using(var s=d.CreateDbContext("b",b.AccountId)){var tag=Tag(b.AccountId,"geology","Foreign Geo");s.TagTypes.Add(tag);await s.SaveChangesAsync();id=tag.Id;}await using var db=d.CreateDbContext("a",a.AccountId);var p=new CaveImportPlanner(db,db.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.CaveHeader+"\nTags,County A,A01,22,AA,,,,,,,1,Foreign Geo,,,,,,,false,,\n");var plan=await p.PlanAsync(csv,false);Assert.DoesNotContain(Assert.Single(plan.Caves).Tags,x=>x.TagTypeId==id);Assert.Contains(plan.TagCreations,x=>x.Name=="Foreign Geo");}
    [Fact] public async Task FullInsertOwnsCaveScalarsAndAllSupportedTagRoles()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(FullInsertOwnsCaveScalarsAndAllSupportedTagRoles));var t=await IntegrationTestData.SeedTenantAsync(d,'a');await using var db=d.CreateDbContext("a",t.AccountId);var p=new CaveImportPlanner(db,db.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.CaveHeader+"\nFull,County A,A01,30,AA,Alt,Map,Cart,123.5,45.5,20.5,4,Limestone,Mississippian,Plateau,Artifact,Bats,2026-08-01,Reporter,true,Interesting,Full narrative\n");var plan=await p.PlanAsync(csv,false);var row=Assert.Single(plan.Caves);await Execute(db,plan,"full.csv");var snap=await new CavePublishedSnapshotReader(db,db.RequestUser).BuildAsync(row.Id);Assert.Equal(123.5,snap.LengthFeet);Assert.Equal("Full narrative",snap.Narrative);Assert.True(snap.IsArchived);Assert.Equal(9,snap.Tags.Select(x=>x.Role).Distinct().Count());}
    [Fact] public async Task SyncUpdatePreservesEntranceAndFile()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(SyncUpdatePreservesEntranceAndFile));var t=await IntegrationTestData.SeedTenantAsync(d,'a');await SeedEntrance(d,t,"preserved");await using(var seed=d.CreateDbContext("a",t.AccountId)){var f=await seed.Files.SingleAsync(x=>x.Id==t.FileId);f.CaveId=t.CaveId;await seed.SaveChangesAsync();}await using var db=d.CreateDbContext("a",t.AccountId);var p=new CaveImportPlanner(db,db.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.CaveHeader+"\nUpdated,County A,A01,1,AA,,,,200,50,12,2,,,,,,2026-08-01,,false,,Updated\n");var plan=await p.PlanAsync(csv,true);await Execute(db,plan,"update.csv");Assert.True(await db.Entrances.IgnoreQueryFilters().AnyAsync(e=>e.Id=="preserved"));Assert.True(await db.Files.AnyAsync(f=>f.Id==t.FileId&&f.CaveId==t.CaveId));}
    [Fact] public async Task SyncNoChangeIsOmittedAndCreatesNoRevision()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(SyncNoChangeIsOmittedAndCreatesNoRevision));var t=await IntegrationTestData.SeedTenantAsync(d,'a');await using var db=d.CreateDbContext("a",t.AccountId);var p=new CaveImportPlanner(db,db.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.CaveHeader+"\nCave A,County A,A01,1,AA,,,,,,,,,,,,,,,false,,\n");var plan=await p.PlanAsync(csv,true);Assert.Equal(CaveImportAction.NoChange,Assert.Single(plan.Caves).Action);Assert.Empty(plan.CreatePreview(true));var before=await db.CaveRevisions.CountAsync(r=>r.CaveId==t.CaveId);await Execute(db,plan,"no.csv");Assert.Equal(before,await db.CaveRevisions.CountAsync(r=>r.CaveId==t.CaveId));}
    [Fact] public async Task CommitAbortsOnPlannedVersionDrift()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(CommitAbortsOnPlannedVersionDrift));var t=await IntegrationTestData.SeedTenantAsync(d,'a');CaveImportPlan plan;await using(var pctx=d.CreateDbContext("a",t.AccountId)){var p=new CaveImportPlanner(pctx,pctx.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.CaveHeader+"\nPlanned,County A,A01,1,AA,,,,100,10,5,1,,,,,,,,false,,planned\n");plan=await p.PlanAsync(csv,true);}await using(var other=d.CreateDbContext("a",t.AccountId)){var cave=await other.Caves.IgnoreQueryFilters().SingleAsync(c=>c.Id==t.CaveId);cave.Name="Concurrent";await other.SaveChangesAsync();}await using var db=d.CreateDbContext("a",t.AccountId);await Assert.ThrowsAsync<CaveRevisionConflictException>(()=>Execute(db,plan,"conflict.csv"));Assert.False(await db.CaveImportBatches.AnyAsync(b=>b.SourceFileName=="conflict.csv"));}

    private async Task AssertPlanFails(string row,bool sync=false){await using var d=await fixture.CreateDatabaseAsync(Guid.NewGuid().ToString("N"));var t=await IntegrationTestData.SeedTenantAsync(d,'a');await using var db=d.CreateDbContext("a",t.AccountId);var p=new CaveImportPlanner(db,db.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.CaveHeader+"\n"+row+"\n");await Assert.ThrowsAnyAsync<Exception>(()=>p.PlanAsync(csv,sync));}
    private static TagType Tag(string account,string key,string name)=>new(name,key){Id=IdGenerator.Generate(),AccountId=account,IsDefault=false};
    private static async Task Execute(Planarian.Model.Database.PlanarianDbContext db,CaveImportPlan plan,string file){var r=new CavePublishedSnapshotReader(db,db.RequestUser);await new CaveImportExecutor(db,db.RequestUser,r,new ImportRevisionPublisher(db,db.RequestUser)).ExecuteAsync(plan,file);}
    private static async Task SeedEntrance(PostgresTestDatabase d,TenantSeed t,string id){await using var db=d.CreateDbContext("a",t.AccountId);var q=Tag(t.AccountId,TagTypeKeyConstant.LocationQuality,"Survey Grade");db.TagTypes.Add(q);await db.SaveChangesAsync();db.Entrances.Add(new Entrance{Id=id,CaveId=t.CaveId,LocationQualityTagId=q.Id,IsPrimary=true,Location=new Point(new CoordinateZ(-86,35,500)){SRID=4326}});await db.SaveChangesAsync();}
}
