using Microsoft.EntityFrameworkCore;
using NetTopologySuite.Geometries;
using Planarian.Library.Exceptions;
using Planarian.Model.Database.Entities;
using Planarian.Model.Database.Entities.RidgeWalker;
using Planarian.Model.Database.Revisions;
using Planarian.Model.Shared;
using Planarian.Model.Shared.Helpers;
using Planarian.Modules.Caves.Revisions;
using Planarian.Modules.Import.Planning;
using Xunit;

namespace Planarian.Tests;

public sealed class EntranceImportCompatibilityTests(PostgresTestServer fixture):IClassFixture<PostgresTestServer>
{
    [Fact] public async Task MissingLatitudeIsRejectedIndependently()=>await AssertPlanFails("Missing latitude,A01,1,true,,-86,500,Survey Grade,0,,,,,,,");
    [Fact] public async Task MissingLongitudeIsRejectedIndependently()=>await AssertPlanFails("Missing longitude,A01,1,true,35,,500,Survey Grade,0,,,,,,,");
    [Theory][InlineData(91,-86,500,0)][InlineData(-91,-86,500,0)][InlineData(35,181,500,0)][InlineData(35,-181,500,0)][InlineData(35,-86,-1,0)][InlineData(35,-86,500,-1)]
    public async Task NumericValidationMatchesMain(double lat,double lon,double elev,double pit)=>await AssertPlanFails($"Invalid,A01,1,true,{lat},{lon},{elev},Survey Grade,{pit},,,,,,,");
    [Fact] public async Task InvalidOptionalDateBecomesNull()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(InvalidOptionalDateBecomesNull));var t=await TestDataScenarios.CreatePublishedCaveScenarioAsync(d,'a');await using var db=d.CreateDbContext("a",t.AccountId);var p=new EntranceImportPlanningWorkflow(db,db.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.EntranceHeader+"\nTrim,A01,1,true,35,-86,500,Survey Grade,0,,,,not-a-date,,Description\n");var row=Assert.Single((await p.PlanAsync(csv,false)).Entrances);Assert.Null(row.ReportedOn);Assert.Equal("Description",row.Description);}
    [Fact] public async Task ExistingLocationQualityAndMultiValueTagAreReusedCaseInsensitively()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(ExistingLocationQualityAndMultiValueTagAreReusedCaseInsensitively));var t=await TestDataScenarios.CreatePublishedCaveScenarioAsync(d,'a');string qualityId,statusId;await using(var s=d.CreateDbContext("a",t.AccountId)){var quality=Tag(t.AccountId,TagTypeKeyConstant.LocationQuality,"Survey Grade");var status=Tag(t.AccountId,TagTypeKeyConstant.EntranceStatus,"Open");s.TagTypes.AddRange(quality,status);await s.SaveChangesAsync();qualityId=quality.Id;statusId=status.Id;}await using var db=d.CreateDbContext("a",t.AccountId);var p=new EntranceImportPlanningWorkflow(db,db.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.EntranceHeader+"\nCase,A01,1,true,35,-86,500,  survey grade  ,0,\"open, OPEN\",,,,,\n");var plan=await p.PlanAsync(csv,false);Assert.Empty(plan.TagCreations);var planned=Assert.Single(plan.Entrances);Assert.Equal(qualityId,planned.LocationQualityTagId);Assert.Equal("Survey Grade",planned.LocationQualityName);Assert.Equal(statusId,Assert.Single(planned.Tags).TagTypeId);Assert.Equal("Survey Grade",Assert.Single(plan.CreatePreview()).LocationQuality);await Execute(db,plan,"case.csv");db.ChangeTracker.Clear();var snapshot=await new CavePublishedSnapshotRepository(db,db.RequestUser).BuildAsync(t.CaveId);var entrance=Assert.Single(snapshot.Entrances);Assert.Equal(qualityId,entrance.LocationQualityTagId);Assert.Equal("Survey Grade",entrance.LocationQualityNameAtRevision);Assert.Contains(entrance.Tags,x=>x.TagTypeId==statusId&&x.NameAtRevision=="Open");Assert.Equal(2,await db.TagTypes.CountAsync(x=>x.AccountId==t.AccountId&&(x.Key==TagTypeKeyConstant.LocationQuality||x.Key==TagTypeKeyConstant.EntranceStatus)));}
    [Fact] public async Task SameImportCaseVariantsAcrossRowsCreateOneEntranceTag()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(SameImportCaseVariantsAcrossRowsCreateOneEntranceTag));var t=await TestDataScenarios.CreatePublishedCaveScenarioAsync(d,'a');await using var db=d.CreateDbContext("a",t.AccountId);var p=new EntranceImportPlanningWorkflow(db,db.RequestUser);var h=ImportDryRunIntegrationTests.EntranceHeader;await using var csv=ImportDryRunIntegrationTests.CsvStream(h+"\nPrimary,A01,1,true,35,-86,500,Survey Grade,0,Open,,,,,,\nOther,A01,1,false,35.1,-86.1,510,survey grade,0,OPEN,,,,,,\n");var plan=await p.PlanAsync(csv,false);var status=Assert.Single(plan.TagCreations,x=>x.Key==TagTypeKeyConstant.EntranceStatus);Assert.Equal("Open",status.Name);var quality=Assert.Single(plan.TagCreations,x=>x.Key==TagTypeKeyConstant.LocationQuality);Assert.Equal("Survey Grade",quality.Name);Assert.All(plan.Entrances,x=>Assert.Equal(status.Id,Assert.Single(x.Tags).TagTypeId));await Execute(db,plan,"variants.csv");Assert.Single(await db.TagTypes.Where(x=>x.AccountId==t.AccountId&&x.Key==TagTypeKeyConstant.EntranceStatus&&x.Name.ToLower()=="open").ToListAsync());}
    [Fact] public async Task ForeignCustomEntranceTagsRemainIneligibleCaseInsensitively()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(ForeignCustomEntranceTagsRemainIneligibleCaseInsensitively));var a=await TestDataScenarios.CreatePublishedCaveScenarioAsync(d,'a');var b=await TestDataScenarios.CreatePublishedCaveScenarioAsync(d,'b');string foreign;await using(var s=d.CreateDbContext("b",b.AccountId)){var tag=Tag(b.AccountId,TagTypeKeyConstant.EntranceStatus,"Open");s.TagTypes.Add(tag);await s.SaveChangesAsync();foreign=tag.Id;}await using var db=d.CreateDbContext("a",a.AccountId);var p=new EntranceImportPlanningWorkflow(db,db.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.EntranceHeader+"\nCase,A01,1,true,35,-86,500,Survey Grade,0,open,,,,,,\n");var plan=await p.PlanAsync(csv,false);var local=Assert.Single(plan.TagCreations,x=>x.Key==TagTypeKeyConstant.EntranceStatus);Assert.NotEqual(foreign,local.Id);Assert.Contains(Assert.Single(plan.Entrances).Tags,x=>x.TagTypeId==local.Id);await Execute(db,plan,"foreign.csv");Assert.False(await db.EntranceStatusTags.AnyAsync(x=>x.TagTypeId==foreign));Assert.Single(await db.TagTypes.Where(x=>x.AccountId==a.AccountId&&x.Key==TagTypeKeyConstant.EntranceStatus&&x.Name.ToLower()=="open").ToListAsync());}
    [Fact] public async Task FullInsertPersistsScalarsTagsAndPostgisXYZ()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(FullInsertPersistsScalarsTagsAndPostgisXYZ));var t=await TestDataScenarios.CreatePublishedCaveScenarioAsync(d,'a');await using var db=d.CreateDbContext("a",t.AccountId);var p=new EntranceImportPlanningWorkflow(db,db.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.EntranceHeader+"\nMain,A01,1,true,35.123456,-86.654321,612.5,Survey Grade,22.5,Open,Wet,Sink,2026-08-01,Surveyor,Full description\n");var plan=await p.PlanAsync(csv,false);var planned=Assert.Single(plan.Entrances);await Execute(db,plan,"full.csv");var snap=await new CavePublishedSnapshotRepository(db,db.RequestUser).BuildAsync(t.CaveId);var e=Assert.Single(snap.Entrances);Assert.Equal(planned.Id,e.Id);Assert.Equal("Main",e.Name);Assert.True(e.IsPrimary);Assert.Equal(35.123456,e.Latitude!.Value,6);Assert.Equal(-86.654321,e.Longitude!.Value,6);Assert.Equal(612.5,e.Elevation!.Value,6);Assert.Equal(4326,e.Srid);Assert.Equal(22.5,e.PitDepthFeet);Assert.Equal("Survey Grade",e.LocationQualityNameAtRevision);Assert.Equal(planned.LocationQualityTagId,e.LocationQualityTagId);Assert.Equal(new DateTime(2026,8,1,0,0,0,DateTimeKind.Utc),e.ReportedOn);Assert.Equal("Full description",e.Description);AssertTags(e.Tags,(SnapshotTagRole.EntranceStatus,"Open"),(SnapshotTagRole.EntranceHydrology,"Wet"),(SnapshotTagRole.FieldIndication,"Sink"),(SnapshotTagRole.EntranceReportedBy,"Surveyor"));}
    [Fact] public async Task ZeroFinalPrimaryIsRejected()=>await AssertPlanFails("Not Primary,A01,1,false,35,-86,500,Survey Grade,0,,,,,,,");
    [Fact] public async Task MultipleImportedPrimariesAreRejected()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(MultipleImportedPrimariesAreRejected));var t=await TestDataScenarios.CreatePublishedCaveScenarioAsync(d,'a');await using var db=d.CreateDbContext("a",t.AccountId);var p=new EntranceImportPlanningWorkflow(db,db.RequestUser);var h=ImportDryRunIntegrationTests.EntranceHeader;await using var csv=ImportDryRunIntegrationTests.CsvStream(h+"\nP1,A01,1,true,35,-86,500,Survey Grade,0,,,,,,,\nP2,A01,1,true,35.1,-86.1,510,Survey Grade,0,,,,,,,\n");await Assert.ThrowsAsync<ApiException>(()=>p.PlanAsync(csv,false));}
    [Fact] public async Task ExistingAndImportedPrimaryConflictIsRejected()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(ExistingAndImportedPrimaryConflictIsRejected));var t=await TestDataScenarios.CreatePublishedCaveScenarioAsync(d,'a');await SeedPrimary(d,t,"existing00");await using var db=d.CreateDbContext("a",t.AccountId);var p=new EntranceImportPlanningWorkflow(db,db.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.EntranceHeader+"\nSecond,A01,1,true,35.1,-86.1,510,Survey Grade,0,,,,,,,\n");await Assert.ThrowsAsync<ApiException>(()=>p.PlanAsync(csv,false));}
    [Fact] public async Task SyncReplacementUsesImportedFinalPrimaryAndReplacesExisting()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(SyncReplacementUsesImportedFinalPrimaryAndReplacesExisting));var t=await TestDataScenarios.CreatePublishedCaveScenarioAsync(d,'a');await SeedPrimary(d,t,"existing00");await using var db=d.CreateDbContext("a",t.AccountId);var p=new EntranceImportPlanningWorkflow(db,db.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.EntranceHeader+"\nReplacement,A01,1,true,35.2,-86.2,520,Survey Grade,7.5,Open,Wet,Sink,2026-08-02,Surveyor,Replacement description\n");var plan=await p.PlanAsync(csv,true);var planned=Assert.Single(plan.Entrances);Assert.Equal(0,Assert.Single(plan.CreatePreview()).EntranceCountChange);var priorRevision=(await db.Caves.IgnoreQueryFilters().SingleAsync(x=>x.Id==t.CaveId)).CurrentRevisionId;await Execute(db,plan,"replace.csv");db.ChangeTracker.Clear();var snap=await new CavePublishedSnapshotRepository(db,db.RequestUser).BuildAsync(t.CaveId);var e=Assert.Single(snap.Entrances);Assert.DoesNotContain(snap.Entrances,x=>x.Id=="existing00");Assert.Equal(planned.Id,e.Id);Assert.Equal("Replacement",e.Name);Assert.True(e.IsPrimary);Assert.Equal(1,snap.Entrances.Count(x=>x.IsPrimary));Assert.Equal(35.2,e.Latitude!.Value,6);Assert.Equal(-86.2,e.Longitude!.Value,6);Assert.Equal(520,e.Elevation!.Value,6);Assert.Equal(4326,e.Srid);Assert.Equal(7.5,e.PitDepthFeet);Assert.Equal("Survey Grade",e.LocationQualityNameAtRevision);Assert.Equal("Replacement description",e.Description);Assert.Equal(new DateTime(2026,8,2,0,0,0,DateTimeKind.Utc),e.ReportedOn);AssertTags(e.Tags,(SnapshotTagRole.EntranceStatus,"Open"),(SnapshotTagRole.EntranceHydrology,"Wet"),(SnapshotTagRole.FieldIndication,"Sink"),(SnapshotTagRole.EntranceReportedBy,"Surveyor"));var cave=await db.Caves.IgnoreQueryFilters().SingleAsync(x=>x.Id==t.CaveId);Assert.NotEqual(priorRevision,cave.CurrentRevisionId);var revision=await db.CaveRevisions.SingleAsync(x=>x.Id==cave.CurrentRevisionId);Assert.Equal(CaveRevisionSource.Import,revision.Source);Assert.Equal(CaveRevisionOperation.Update,revision.Operation);Assert.Equal(CaveSnapshotJson.Serialize(snap),CaveSnapshotJson.Serialize(CaveSnapshotJson.Deserialize(revision.SnapshotJson,revision.SnapshotSchemaVersion)));}
    [Fact] public async Task SyncPreservesUnrelatedCave()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(SyncPreservesUnrelatedCave));var t=await TestDataScenarios.CreatePublishedCaveScenarioAsync(d,'a');await SeedPrimary(d,t,"existing00");string second;await using(var s=d.CreateDbContext("a",t.AccountId)){var c=new Cave{Id="secondcav0",AccountId=t.AccountId,StateId=t.StateId,CountyId=t.CountyId,CountyNumber=2,Name="Second",IsArchived=false};s.Caves.Add(c);await s.SaveChangesAsync();second=c.Id;var q=Tag(t.AccountId,TagTypeKeyConstant.LocationQuality,"Second Quality");s.TagTypes.Add(q);await s.SaveChangesAsync();s.Entrances.Add(new Entrance{Id="secondent0",CaveId=second,LocationQualityTagId=q.Id,Name="Unrelated",Description="Preserve me",ReportedOn=new DateTime(2025,1,2,0,0,0,DateTimeKind.Utc),PitDepthFeet=11,IsPrimary=true,Location=new Point(new CoordinateZ(-86,35,500)){SRID=4326}});await s.SaveChangesAsync();}await using var db=d.CreateDbContext("a",t.AccountId);var reader=new CavePublishedSnapshotRepository(db,db.RequestUser);var before=await reader.BuildAsync(second);var caveBefore=await db.Caves.IgnoreQueryFilters().AsNoTracking().SingleAsync(x=>x.Id==second);var p=new EntranceImportPlanningWorkflow(db,db.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.EntranceHeader+"\nReplacement,A01,1,true,35.2,-86.2,520,Survey Grade,0,,,,,,,\n");var plan=await p.PlanAsync(csv,true);await Execute(db,plan,"sync.csv");db.ChangeTracker.Clear();var after=await reader.BuildAsync(second);var caveAfter=await db.Caves.IgnoreQueryFilters().AsNoTracking().SingleAsync(x=>x.Id==second);Assert.Equal(CaveSnapshotJson.Serialize(before),CaveSnapshotJson.Serialize(after));Assert.Equal(caveBefore.Version,caveAfter.Version);Assert.Equal(caveBefore.CurrentRevisionId,caveAfter.CurrentRevisionId);}
    [Fact] public async Task CommitAbortsIfTargetCaveChangesAfterPlanning()
    {await using var d=await fixture.CreateDatabaseAsync(nameof(CommitAbortsIfTargetCaveChangesAfterPlanning));var t=await TestDataScenarios.CreatePublishedCaveScenarioAsync(d,'a');EntranceImportPlan plan;await using(var pctx=d.CreateDbContext("a",t.AccountId)){var p=new EntranceImportPlanningWorkflow(pctx,pctx.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.EntranceHeader+"\nPlanned,A01,1,true,35,-86,500,Survey Grade,0,,,,,,,\n");plan=await p.PlanAsync(csv,false);}await using(var o=d.CreateDbContext("a",t.AccountId)){var c=await o.Caves.IgnoreQueryFilters().SingleAsync(x=>x.Id==t.CaveId);c.Name="Concurrent";await o.SaveChangesAsync();}await using var db=d.CreateDbContext("a",t.AccountId);await Assert.ThrowsAsync<CaveRevisionConflictException>(()=>Execute(db,plan,"conflict.csv"));Assert.Empty(await db.Entrances.IgnoreQueryFilters().Where(e=>e.CaveId==t.CaveId).ToListAsync());}

    private async Task AssertPlanFails(string row){await using var d=await fixture.CreateDatabaseAsync(Guid.NewGuid().ToString("N"));var t=await TestDataScenarios.CreatePublishedCaveScenarioAsync(d,'a');await using var db=d.CreateDbContext("a",t.AccountId);var p=new EntranceImportPlanningWorkflow(db,db.RequestUser);await using var csv=ImportDryRunIntegrationTests.CsvStream(ImportDryRunIntegrationTests.EntranceHeader+"\n"+row+"\n");await Assert.ThrowsAsync<ApiException>(()=>p.PlanAsync(csv,false));}
    private static TagType Tag(string account,string key,string name)=>new(name,key){Id=IdGenerator.Generate(),AccountId=account,IsDefault=false};
    private static void AssertTags(IReadOnlyList<SnapshotTagReference> actual,params (SnapshotTagRole Role,string Name)[] expected)=>Assert.Equal(expected.OrderBy(x=>x.Role).ThenBy(x=>x.Name).Select(x=>$"{x.Role}:{x.Name}"),actual.OrderBy(x=>x.Role).ThenBy(x=>x.NameAtRevision).Select(x=>$"{x.Role}:{x.NameAtRevision}"));
    private static async Task Execute(Planarian.Model.Database.PlanarianDbContext db,EntranceImportPlan plan,string file){var r=new CavePublishedSnapshotRepository(db,db.RequestUser);await new EntranceImportExecutionRepository(db,db.RequestUser,r,new CaveImportRevisionRepository(db,db.RequestUser)).ExecuteAsync(plan,file);}
    private static async Task SeedPrimary(PostgresTestDatabase d,PublishedCaveScenario t,string id){await using var db=d.CreateDbContext("a",t.AccountId);var q=Tag(t.AccountId,TagTypeKeyConstant.LocationQuality,"Survey Grade");db.TagTypes.Add(q);await db.SaveChangesAsync();db.Entrances.Add(new Entrance{Id=id,CaveId=t.CaveId,LocationQualityTagId=q.Id,IsPrimary=true,Location=new Point(new CoordinateZ(-86,35,500)){SRID=4326}});await db.SaveChangesAsync();}
}
