import { AddCaveVm } from "../Models/AddCaveVm";
import { CaveVm } from "../Models/CaveVm";

export const caveToForm = (cave: CaveVm): AddCaveVm => ({
  id: cave.id,
  name: cave.name,
  alternateNames: cave.alternateNames,
  countyId: cave.countyId,
  stateId: cave.stateId,
  countyDisplayId: cave.countyDisplayId,
  countyNumber: cave.countyNumber,
  isCountyNumberManuallySet: false,
  useFirstAvailableCountyNumber: false,
  lengthFeet: cave.lengthFeet,
  depthFeet: cave.depthFeet,
  maxPitDepthFeet: cave.maxPitDepthFeet,
  numberOfPits: cave.numberOfPits,
  narrative: cave.narrative,
  reportedOn: cave.reportedOn,
  entrances: cave.entrances.map((entrance) => ({
    id: entrance.id,
    isPrimary: entrance.isPrimary,
    locationQualityTagId: entrance.locationQualityTagId,
    name: entrance.name,
    description: entrance.description,
    latitude: entrance.latitude,
    longitude: entrance.longitude,
    elevationFeet: entrance.elevationFeet,
    reportedOn: entrance.reportedOn,
    pitFeet: entrance.pitFeet,
    entranceStatusTagIds: entrance.entranceStatusTagIds,
    fieldIndicationTagIds: entrance.fieldIndicationTagIds,
    entranceHydrologyTagIds: entrance.entranceHydrologyTagIds,
    reportedByNameTagIds: entrance.reportedByNameTagIds,
    entranceOtherTagIds: [],
  })),
  geologyTagIds: cave.geologyTagIds,
  files: cave.files,
  reportedByNameTagIds: cave.reportedByNameTagIds,
  biologyTagIds: cave.biologyTagIds,
  archeologyTagIds: cave.archeologyTagIds,
  cartographerNameTagIds: cave.cartographerNameTagIds,
  mapStatusTagIds: cave.mapStatusTagIds,
  geologicAgeTagIds: cave.geologicAgeTagIds,
  physiographicProvinceTagIds: cave.physiographicProvinceTagIds,
  otherTagIds: cave.otherTagIds,
});
