import { AddCaveVm } from "../Models/AddCaveVm";
import { CaveVm } from "../Models/CaveVm";
import { CaveFileSnapshotVm, CaveSnapshotVm, SnapshotTagReference } from "../Models/CaveRevisionVm";
import { CountyNumberIntent } from "../Models/CaveChangeRequestVm";

export const caveToForm = (cave: CaveVm): AddCaveVm => ({
  id: cave.id,
  name: cave.name,
  alternateNames: cave.alternateNames,
  countyId: cave.countyId,
  stateId: cave.stateId,
  countyDisplayId: cave.countyDisplayId,
  countyNumber: cave.countyNumber,
  isCountyNumberManuallySet: false,
  useFirstAvailableCountyNumber: false,
  lengthFeet: cave.lengthFeet,
  depthFeet: cave.depthFeet,
  maxPitDepthFeet: cave.maxPitDepthFeet,
  numberOfPits: cave.numberOfPits,
  narrative: cave.narrative,
  reportedOn: cave.reportedOn,
  entrances: cave.entrances.map((entrance) => ({
    id: entrance.id,
    isPrimary: entrance.isPrimary,
    locationQualityTagId: entrance.locationQualityTagId,
    name: entrance.name,
    description: entrance.description,
    latitude: entrance.latitude,
    longitude: entrance.longitude,
    elevationFeet: entrance.elevationFeet,
    reportedOn: entrance.reportedOn,
    pitFeet: entrance.pitFeet,
    entranceStatusTagIds: entrance.entranceStatusTagIds,
    fieldIndicationTagIds: entrance.fieldIndicationTagIds,
    entranceHydrologyTagIds: entrance.entranceHydrologyTagIds,
    reportedByNameTagIds: entrance.reportedByNameTagIds,
    entranceOtherTagIds: entrance.entranceOtherTagIds,
  })),
  geologyTagIds: cave.geologyTagIds,
  files: cave.files,
  reportedByNameTagIds: cave.reportedByNameTagIds,
  biologyTagIds: cave.biologyTagIds,
  archeologyTagIds: cave.archeologyTagIds,
  cartographerNameTagIds: cave.cartographerNameTagIds,
  mapStatusTagIds: cave.mapStatusTagIds,
  geologicAgeTagIds: cave.geologicAgeTagIds,
  physiographicProvinceTagIds: cave.physiographicProvinceTagIds,
  otherTagIds: cave.otherTagIds,
});

const tagIds = (tags: SnapshotTagReference[], role: string) =>
  tags.filter((tag) => tag.role === role).map((tag) => tag.tagTypeId);

export const snapshotToForm = (snapshot: CaveSnapshotVm, countyNumberIntent?: CountyNumberIntent,
  requestedCountyNumber?: number, additionalFiles: CaveFileSnapshotVm[] = []): AddCaveVm => ({
  id: snapshot.caveId,
  name: snapshot.name,
  alternateNames: snapshot.alternateNames,
  countyId: snapshot.county.id,
  stateId: snapshot.state.id,
  countyDisplayId: snapshot.county.displayIdAtRevision,
  countyNumber: countyNumberIntent === "Manual" ? requestedCountyNumber ?? snapshot.countyNumber : snapshot.countyNumber,
  isCountyNumberManuallySet: countyNumberIntent === "Manual",
  useFirstAvailableCountyNumber: countyNumberIntent === "FirstAvailable",
  lengthFeet: snapshot.lengthFeet ?? null,
  depthFeet: snapshot.depthFeet ?? null,
  maxPitDepthFeet: snapshot.maxPitDepthFeet ?? null,
  numberOfPits: snapshot.numberOfPits ?? null,
  narrative: snapshot.narrative ?? null,
  reportedOn: snapshot.reportedOn ?? null,
  entrances: snapshot.entrances.map((entrance) => ({
    id: entrance.id,
    isPrimary: entrance.isPrimary,
    locationQualityTagId: entrance.locationQualityTagId,
    name: entrance.name ?? null,
    description: entrance.description ?? null,
    latitude: entrance.latitude ?? 0,
    longitude: entrance.longitude ?? 0,
    elevationFeet: entrance.elevation ?? 0,
    reportedOn: entrance.reportedOn ?? null,
    pitFeet: entrance.pitDepthFeet ?? null,
    entranceStatusTagIds: tagIds(entrance.tags, "EntranceStatus"),
    fieldIndicationTagIds: tagIds(entrance.tags, "FieldIndication"),
    entranceHydrologyTagIds: tagIds(entrance.tags, "EntranceHydrology"),
    reportedByNameTagIds: tagIds(entrance.tags, "EntranceReportedBy"),
    entranceOtherTagIds: tagIds(entrance.tags, "EntranceOther"),
  })),
  geologyTagIds: tagIds(snapshot.tags, "Geology"),
  files: [...snapshot.files, ...additionalFiles.filter(file => !snapshot.files.some(existing => existing.id === file.id))].map((file) => ({
    id: file.id,
    fileTypeTagId: file.fileTypeTagId,
    displayName: file.displayName ?? null,
    fileTypeKey: file.fileTypeNameAtRevision,
  })),
  reportedByNameTagIds: tagIds(snapshot.tags, "CaveReportedBy"),
  biologyTagIds: tagIds(snapshot.tags, "Biology"),
  archeologyTagIds: tagIds(snapshot.tags, "Archeology"),
  cartographerNameTagIds: tagIds(snapshot.tags, "Cartographer"),
  mapStatusTagIds: tagIds(snapshot.tags, "MapStatus"),
  geologicAgeTagIds: tagIds(snapshot.tags, "GeologicAge"),
  physiographicProvinceTagIds: tagIds(snapshot.tags, "PhysiographicProvince"),
  otherTagIds: tagIds(snapshot.tags, "CaveOther"),
});
