name: "Deploy Development"

on:
  push:
    branches:
      - main
    paths:
      - "Planarian/Planarian/**"
      - "Planarian.Web/**"
  pull_request:
    branches:
      - main
    paths:
      - "Planarian/Planarian/**"
      - "Planarian.Web/**"
  workflow_dispatch:

jobs:
  build_and_deploy:
    strategy:
      matrix:
        project: ["api", "web"]
        include:
          - project: "api"
            runs-on: "ubuntu-latest"
            name: "Build and Deploy .NET Core API"
          - project: "web"
            runs-on: "ubuntu-latest"
            name: "Build and Deploy Job"
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.name }}
    environment:
      name: Development
    steps:
      - name: Checkout Repository
        uses: ./.github/actions/checkout-repo

      - name: Build and Deploy API
        if: matrix.project == 'api'
        uses: ./.github/actions/build-deploy-api

      - name: Build and Deploy Web
        if: matrix.project == 'web'
        uses: ./.github/actions/build-deploy-web
