name: Prettier

on: [push, pull_request]

jobs:
  run-prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm install --save-dev prettier @typescript-eslint/parser @typescript-eslint/eslint-plugin
    - run: npx prettier --write "Planarian.Web/src/*.{js,jsx,ts,tsx}"
